DROP TABLE IF EXISTS Transactions;
CREATE TABLE IF NOT EXISTS"Transactions" (
	"_ID"	         INTEGER NOT NULL,
	"Date"	         INTEGER NOT NULL,
	"DISCRIPTION"	 TEXT NOT NULL,
	"GAS"	         NUMERIC NOT NULL,
	"SERVICE"	     NUMERIC NOT NULL,
	"JOHN"	         NUMERIC NOT NULL,
	"PASTOR"	     NUMERIC NOT NULL,
	"MED"	         NUMERIC NOT NULL,
	"SCHOOL"	     NUMERIC NOT NULL,
	"MISC"	         NUMERIC NOT NULL,
	"TAX"	         NUMERIC NOT NULL,
	"SAVINGS"	     NUMERIC NOT NULL,
	"SAVINGS_OTHER"  NUMERIC NOT NULL,
	PRIMARY KEY("_ID" AUTOINCREMENT)
)